name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  solver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'

      # confirm the gradle wrapper jar checksum matches known-safe value
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run solver headlessly 100 times
        run: |
          gradle run -PchooseMain=main.TXTmain --args="-n 100"